/**
 * Order Details
 * Retrieve information about current and past orders.
 *
 * The version of the OpenAPI document: v3
 * Contact: api.contact@digikey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.jastrab.model.error

import com.fasterxml.jackson.annotation.JsonProperty
import net.jastrab.model.error.ApiValidationError

/**
 *
 * @param errorResponseVersion
 * @param statusCode
 * @param errorMessage
 * @param errorDetails
 * @param requestId
 * @param validationErrors
 */

data class ApiErrorResponse(
    @JsonProperty("ErrorResponseVersion")
    val errorResponseVersion: String? = null,
    @JsonProperty("StatusCode")
    val statusCode: Int? = null,
    @JsonProperty("ErrorMessage")
    val errorMessage: String? = null,
    @JsonProperty("ErrorDetails")
    val errorDetails: String? = null,
    @JsonProperty("RequestId")
    val requestId: String? = null,
    @JsonProperty("ValidationErrors")
    val validationErrors: List<ApiValidationError> = ArrayList()
)
