/**
 * Order Details
 * Retrieve information about current and past orders.
 *
 * The version of the OpenAPI document: v3
 * Contact: api.contact@digikey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.jastrab.digikey.model.ordersupport

import com.fasterxml.jackson.databind.PropertyNamingStrategy
import com.fasterxml.jackson.databind.annotation.JsonNaming
import java.math.BigDecimal


/**
 * Information on a single line item of an order
 * @param digiKeyPartNumber The Digi-Key part number.
 * @param productDescription Catalog description of the product.
 * @param quantity The total quantity for the order.
 * @param customerReference Freeform customer reference
 * @param unitPrice The price for a single unit of this product.
 * @param totalPrice Price of ordered quantity of the product.
 * @param quantityBackorder The quantity on backorder
 * @param quantityShipped The quantity shipped
 * @param invoiceId The Invoice Id for this shipment
 */

@JsonNaming(PropertyNamingStrategy.UpperCamelCaseStrategy::class)
data class LineItem(
    /* The Digi-Key part number. */
    val digiKeyPartNumber: String,
    /* Catalog description of the product. */
    val productDescription: String,
    /* Name of the manufacturer of this item */
    val manufacturer: String,
    /* The manufacturer part number for this item */
    val manufacturerPartNumber: String,
    val countryOfOrigin: String?,
    /* The total quantity for the order. */
    val quantity: Int,
    /* Free-form customer reference */
    val customerReference: String?,
    /* The price for a single unit of this product. */
    val unitPrice: BigDecimal,
    /* Price of ordered quantity of the product. */
    val totalPrice: BigDecimal,
    /* The quantity on backorder */
    val quantityBackorder: Int?,
    /* The quantity shipped */
    val quantityShipped: Long?,
    /* The Invoice Id for this shipment */
    val invoiceId: Long?
)

