/**
 * Order Details
 * Retrieve information about current and past orders.
 *
 * The version of the OpenAPI document: v3
 * Contact: api.contact@digikey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.jastrab.digikey.model.ordersupport

import com.fasterxml.jackson.annotation.JsonProperty
import java.math.BigDecimal


/**
 * Information on a single line item of an order
 * @param digiKeyPartNumber The Digi-Key part number.
 * @param productDescription Catalog description of the product.
 * @param quantity The total quantity for the order.
 * @param customerReference Freeform customer reference
 * @param unitPrice The price for a single unit of this product.
 * @param totalPrice Price of ordered quantity of the product.
 * @param quantityBackorder The quantity on backorder
 * @param quantityShipped The quantity shipped
 * @param invoiceId The Invoice Id for this shipment
 */

data class LineItem(
    /* The Digi-Key part number. */
    @JsonProperty("DigiKeyPartNumber")
    val digiKeyPartNumber: String? = null,
    /* Catalog description of the product. */
    @JsonProperty("ProductDescription")
    val productDescription: String? = null,
    /* The total quantity for the order. */
    @JsonProperty("Quantity")
    val quantity: Int? = null,
    /* Free-form customer reference */
    @JsonProperty("CustomerReference")
    val customerReference: String? = null,
    /* The price for a single unit of this product. */
    @JsonProperty("UnitPrice")
    val unitPrice: BigDecimal? = null,
    /* Price of ordered quantity of the product. */
    @JsonProperty("TotalPrice")
    val totalPrice: BigDecimal? = null,
    /* The quantity on backorder */
    @JsonProperty("QuantityBackorder")
    val quantityBackorder: Int? = null,
    /* The quantity shipped */
    @JsonProperty("QuantityShipped")
    val quantityShipped: Long? = null,
    /* The Invoice Id for this shipment */
    @JsonProperty("InvoiceId")
    val invoiceId: Long? = null
)

