/**
 * Order Details
 * Retrieve information about current and past orders.
 *
 * The version of the OpenAPI document: v3
 * Contact: api.contact@digikey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.jastrab.digikey.model.ordersupport

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.databind.PropertyNamingStrategy
import com.fasterxml.jackson.databind.annotation.JsonNaming

/**
 * OrderStatus response model returned from v3/Status/{SalesorderId} endpoint
 * @param salesorderId Id for this order
 * @param customerId Your Digi-Key customer Id
 * @param billingAccount Net Terms billing account number used for the order.
 * @param email Email Address
 * @param purchaseOrder Freeform purchase order
 * @param paymentMethod Payment method for the order
 * @param shippingMethod Shipping method requested
 * @param backorderShippingMethod Backorder shipping method requested
 * @param shipperAccountNumber Account number with the shipper
 * @param backorderShipperAccountNumber Account number with the backorder shipper
 * @param shipmentType Can be Immediate, Double or Single. If Immediate, all items will ship as available. If Double, all items immediately available will ship, and other items will be held untill all are available. If Single, entire order is held untill all items are available.
 * @param currency ISO code for currency used in the order.
 * @param shippingAddress
 * @param billingAddress
 * @param shippingDetails List of shipping details
 * @param lineItems List of line items
 */

@JsonNaming(PropertyNamingStrategy.UpperCamelCaseStrategy::class)
data class OrderStatus(
    /* Id for this order */
    val salesorderId: String,
    val supplier: String?,
    /* Your Digi-Key customer Id */
    val customerId: String,
    /* Net Terms billing account number used for the order. */
    val billingAccount: Int?,
    /* Email Address */
    val email: String?,
    /* Freeform purchase order */
    val purchaseOrder: String?,
    /* Payment method for the order */
    val paymentMethod: String?,
    /* Shipping method requested */
    val shippingMethod: String?,
    /* Backorder shipping method requested */
    val backorderShippingMethod: String?,
    /* Account number with the shipper */
    val shipperAccountNumber: String?,
    /* Account number with the backorder shipper */
    val backorderShipperAccountNumber: String?,
    /* Can be Immediate, Double or Single. If Immediate, all items will ship as available. If Double, all items immediately available will ship, and other items will be held untill all are available. If Single, entire order is held untill all items are available. */
    val shipmentType: String?,
    /* ISO code for currency used in the order. */
    val currency: String?,
    val shippingAddress: Address?,
    val billingAddress: Address?,
    /* List of shipping details */
    val shippingDetails: List<ShippingDetail> = ArrayList(),
    /* List of line items */
    val lineItems: List<LineItem> = ArrayList()
)

