/**
 * Order Details
 * Retrieve information about current and past orders.
 *
 * The version of the OpenAPI document: v3
 * Contact: api.contact@digikey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.jastrab.digikey.model.ordersupport

import com.fasterxml.jackson.annotation.JsonProperty


/**
 * Information pertaining to a single Salesorder, returned from the v3/History endpoint
 * @param salesorderId The Salesorder Id. You can use this Id to look up details on the order.
 * @param customerId The CustomerId associated with the Salesorder
 * @param dateEntered Date in which the order was entered in ISO 8601 format.
 * @param purchaseOrder Purchase order if available
 */

data class SalesorderHistoryItem(
    /* The Salesorder Id. You can use this Id to look up details on the order. */
    @JsonProperty("SalesorderId")
    val salesorderId: String,
    /* The CustomerId associated with the Salesorder */
    @JsonProperty("CustomerId")
    val customerId: String,
    /* Date in which the order was entered in ISO 8601 format. */
    @JsonProperty("DateEntered")
    val dateEntered: String? = null,
    /* Purchase order if available */
    @JsonProperty("PurchaseOrder")
    val purchaseOrder: String? = null
)

