/**
 * Order Details
 * Retrieve information about current and past orders.
 *
 * The version of the OpenAPI document: v3
 * Contact: api.contact@digikey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.jastrab.digikey.model.error

import com.fasterxml.jackson.annotation.JsonProperty


/**
 *
 * @param field
 * @param message
 */

data class ApiValidationError(
    @JsonProperty("Field")
    val field: String? = null,
    @JsonProperty("Message")
    val message: String? = null
)

