/**
 * Order Details
 * Retrieve information about current and past orders.
 *
 * The version of the OpenAPI document: v3
 * Contact: api.contact@digikey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.jastrab.model.ordersupport

import com.fasterxml.jackson.annotation.JsonProperty


/**
 * Shipping information for a single shipment of an order
 * @param carrier Name of the carrier
 * @param carrierPackageId Id assigned by the carrier
 * @param dateTransaction Date that tracking number was generated in ISO 8601 format
 * @param shippingMethod Shipping method used by this shipment
 * @param trackingUrl
 * @param invoiceId The Invoice Id for this shipment
 * @param canceledOrVoided Whether this individual detail has been canceled or voided.
 */

data class ShippingDetail(
    /* Name of the carrier */
    @JsonProperty("Carrier")
    val carrier: String? = null,
    /* Id assigned by the carrier */
    @JsonProperty("CarrierPackageId")
    val carrierPackageId: String? = null,
    /* Date that tracking number was generated in ISO 8601 format */
    @JsonProperty("DateTransaction")
    val dateTransaction: String? = null,
    /* Shipping method used by this shipment */
    @JsonProperty("ShippingMethod")
    val shippingMethod: String? = null,
    @JsonProperty("TrackingUrl")
    val trackingUrl: String? = null,
    /* The Invoice Id for this shipment */
    @JsonProperty("InvoiceId")
    val invoiceId: Int? = null,
    /* Whether this individual detail has been canceled or voided. */
    @JsonProperty("CanceledOrVoided")
    val canceledOrVoided: Boolean? = null
)

