/**
 * PartSearch Api
 * Search for products and retrieve details and pricing.
 *
 * The version of the OpenAPI document: v3
 * Contact: api.support@digikey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.jastrab.digikey.model.partsearch

import com.fasterxml.jackson.annotation.JsonProperty
import java.math.BigDecimal

/**
 * Response for Digi-Reel Pricing Request
 * @param reelingFee Fee per reel ordered.
 * @param unitPrice Price of a single unit of the product.
 * @param extendedPrice The total price of the requested reels and the reeling fee.
 * @param requestedQuantity The passed in quantity of the product you are looking to create a Digi-Reel with.
 * @param searchLocaleUsed
 */

data class DigiReelPricing(
    /* Fee per reel ordered. */
    @JsonProperty("ReelingFee")
    val reelingFee: BigDecimal? = null,
    /* Price of a single unit of the product. */
    @JsonProperty("UnitPrice")
    val unitPrice: BigDecimal? = null,
    /* The total price of the requested reels and the reeling fee. */
    @JsonProperty("ExtendedPrice")
    val extendedPrice: BigDecimal? = null,
    /* The passed in quantity of the product you are looking to create a Digi-Reel with. */
    @JsonProperty("RequestedQuantity")
    val requestedQuantity: Int? = null,
    @JsonProperty("SearchLocaleUsed")
    val searchLocaleUsed: IsoSearchLocale? = null
)

