/**
* PartSearch Api
* Search for products and retrieve details and pricing.
*
* The version of the OpenAPI document: v3
* Contact: api.support@digikey.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package net.jastrab.digikey.model.partsearch

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The validated locale that was used for the search. If the provided locale was invalid, this will show the corrections.
 * @param site The site used for the API call.
 * @param language The language used for the API call. If the provided language is not valid for the site, it will be set to the site default.
 * @param currency The currency used for the API call. If the provided currency is not valid for the site, it will be set to the site default.
 * @param shipToCountry The destination for shipping the product. This is used for tariffs and regional pricing.
 */

data class IsoSearchLocale (
    /* The site used for the API call. */
    @JsonProperty("Site")
    val site: String? = null,
    /* The language used for the API call. If the provided language is not valid for the site, it will be set to the site default. */
    @JsonProperty("Language")
    val language: String? = null,
    /* The currency used for the API call. If the provided currency is not valid for the site, it will be set to the site default. */
    @JsonProperty("Currency")
    val currency: String? = null,
    /* The destination for shipping the product. This is used for tariffs and regional pricing. */
    @JsonProperty("ShipToCountry")
    val shipToCountry: String? = null
)

