/**
 * PartSearch Api
 * Search for products and retrieve details and pricing.
 *
 * The version of the OpenAPI document: v3
 * Contact: api.support@digikey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.jastrab.digikey.model.partsearch

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Response model for a keyword search request.
 * @param products List of products returned by KeywordSearch
 * @param productsCount Total number of matching products found.
 * @param exactManufacturerProducts List of products that are exact ManufacturerPartNumber matches.
 * @param exactManufacturerProductsCount Number of exact ManufacturerPartNumber matches.
 * @param exactDigiKeyProduct
 * @param limitedTaxonomy
 * @param filterOptions Available filters for narrowing down results.
 * @param searchLocaleUsed
 */

data class KeywordSearchResponse(
    /* List of products returned by KeywordSearch */
    @JsonProperty("Products")
    val products: List<Product> = ArrayList(),
    /* Total number of matching products found. */
    @JsonProperty("ProductsCount")
    val productsCount: Int? = null,
    /* List of products that are exact ManufacturerPartNumber matches. */
    @JsonProperty("ExactManufacturerProducts")
    val exactManufacturerProducts: List<Product> = ArrayList(),
    /* Number of exact ManufacturerPartNumber matches. */
    @JsonProperty("ExactManufacturerProductsCount")
    val exactManufacturerProductsCount: Int? = null,
    @JsonProperty("ExactDigiKeyProduct")
    val exactDigiKeyProduct: Product? = null,
    @JsonProperty("LimitedTaxonomy")
    val limitedTaxonomy: LimitedTaxonomy? = null,
    /* Available filters for narrowing down results. */
    @JsonProperty("FilterOptions")
    val filterOptions: List<LimitedParameter> = ArrayList(),
    @JsonProperty("SearchLocaleUsed")
    val searchLocaleUsed: IsoSearchLocale? = null
)

