/**
 * PartSearch Api
 * Search for products and retrieve details and pricing.
 *
 * The version of the OpenAPI document: v3
 * Contact: api.support@digikey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.jastrab.digikey.model.partsearch


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * The taxonomy limited to products in the response.
 * @param children List of taxonomies contained within this taxonomy.
 * @param productCount The number of products contained within this taxonomy.
 * @param newProductCount The number of new products contained within this taxonomy.
 * @param parameterId The Id of the parameter.
 * @param valueId The Id of the value.
 * @param parameter The name of the parameter.
 * @param value The name of the value.
 */

data class LimitedTaxonomy(
    /* List of taxonomies contained within this taxonomy. */
    @JsonProperty("Children")
    val children: List<LimitedTaxonomy> = ArrayList(),
    /* The number of products contained within this taxonomy. */
    @JsonProperty("ProductCount")
    val productCount: Int? = null,
    /* The number of new products contained within this taxonomy. */
    @JsonProperty("NewProductCount")
    val newProductCount: Int? = null,
    /* The Id of the parameter. */
    @JsonProperty("ParameterId")
    val parameterId: Int? = null,
    /* The Id of the value. */
    @JsonProperty("ValueId")
    val valueId: String? = null,
    /* The name of the parameter. */
    @JsonProperty("Parameter")
    val parameter: String? = null,
    /* The name of the value. */
    @JsonProperty("Value")
    val value: String? = null
)

