/**
 * PartSearch Api
 * Search for products and retrieve details and pricing.
 *
 * The version of the OpenAPI document: v3
 * Contact: api.support@digikey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.jastrab.digikey.model.partsearch

import com.fasterxml.jackson.annotation.JsonProperty


/**
 * A filter used to refine a keyword search on any parameter.
 * @param parameterId The parameter identifier.
 * @param valueId The value identifier.
 */

data class ParametricFilter(
    /* The parameter identifier. */
    @JsonProperty("ParameterId")
    val parameterId: Int,
    /* The value identifier. */
    @JsonProperty("ValueId")
    val valueId: String
)

