/**
* PartSearch Api
* Search for products and retrieve details and pricing.
*
* The version of the OpenAPI document: v3
* Contact: api.support@digikey.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package net.jastrab.digikey.model.partsearch


import com.fasterxml.jackson.annotation.JsonProperty
import java.math.BigDecimal

/**
 * PriceBreak of a product. Note that all pricing when keyword searching is cached catalog pricing.
 * @param breakQuantity Price tiers based on the available quantities of the product.
 * @param unitPrice Price of a single unit of the product at this break.
 * @param totalPrice Price of BreakQuantity units of the product.
 */

data class PriceBreak (
    /* Price tiers based on the available quantities of the product. */
    @JsonProperty("BreakQuantity")
    val breakQuantity: Int? = null,
    /* Price of a single unit of the product at this break. */
    @JsonProperty("UnitPrice")
    val unitPrice: BigDecimal? = null,
    /* Price of BreakQuantity units of the product. */
    @JsonProperty("TotalPrice")
    val totalPrice: BigDecimal? = null
)

