/**
 * PartSearch Api
 * Search for products and retrieve details and pricing.
 *
 * The version of the OpenAPI document: v3
 * Contact: api.support@digikey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.jastrab.model.partsearch

import com.fasterxml.jackson.annotation.JsonProperty
import java.math.BigDecimal

/**
 * A limited product model used for associated products.
 * @param digiKeyPartNumber The Digi-Key part number.
 * @param quantityAvailable Quantity of the product available for immediate sale.
 * @param manufacturerPartNumber The manufacturer part number. Note that some manufacturer part numbers may be used by multiple manufacturers for different parts.
 * @param manufacturer
 * @param productDescription Catalog description of the product.
 * @param packaging
 * @param minimumOrderQuantity The minimum quantity to order from Digi-Key.
 * @param nonStock Indicates this product is a non stock product.
 * @param quantityOnOrder Quantity of this product ordered but not immediately available.
 * @param manufacturerPublicQuantity Quantity of this product available to order from manufacturer.
 * @param unitPrice The price for a single unit of this product.
 * @param productUrl Full URL of the Digi-Key catalog page to purchase the product. This is based on your provided Locale values.
 */

data class AssociatedProduct(
    /* The Digi-Key part number. */
    @JsonProperty("DigiKeyPartNumber")
    val digiKeyPartNumber: String? = null,
    /* Quantity of the product available for immediate sale. */
    @JsonProperty("QuantityAvailable")
    val quantityAvailable: Int? = null,
    /* The manufacturer part number. Note that some manufacturer part numbers may be used by multiple manufacturers for
    different parts. */
    @JsonProperty("ManufacturerPartNumber")
    val manufacturerPartNumber: String? = null,
    @JsonProperty("Manufacturer")
    val manufacturer: PidVid? = null,
    /* Catalog description of the product. */
    @JsonProperty("ProductDescription")
    val productDescription: String? = null,
    @JsonProperty("Packaging")
    val packaging: PidVid? = null,
    /* The minimum quantity to order from Digi-Key. */
    @JsonProperty("MinimumOrderQuantity")
    val minimumOrderQuantity: Int? = null,
    /* Indicates this product is a non stock product. */
    @JsonProperty("NonStock")
    val nonStock: Boolean? = null,
    /* Quantity of this product ordered but not immediately available. */
    @JsonProperty("QuantityOnOrder")
    val quantityOnOrder: Int? = null,
    /* Quantity of this product available to order from manufacturer. */
    @JsonProperty("ManufacturerPublicQuantity")
    val manufacturerPublicQuantity: Int? = null,
    /* The price for a single unit of this product. */
    @JsonProperty("UnitPrice")
    val unitPrice: BigDecimal? = null,
    /* Full URL of the Digi-Key catalog page to purchase the product. This is based on your provided Locale values. */
    @JsonProperty("ProductUrl")
    val productUrl: String? = null
)

