/**
 * PartSearch Api
 * Search for products and retrieve details and pricing.
 *
 * The version of the OpenAPI document: v3
 * Contact: api.support@digikey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.jastrab.model.partsearch

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Product contained within a Kit.
 * @param associatedProduct
 * @param kitPartQuantity Number of the product in the Kit.
 */

data class KitPart(
    @JsonProperty("AssociatedProduct")
    val associatedProduct: AssociatedProduct? = null,
    /* Number of the product in the Kit. */
    @JsonProperty("KitPartQuantity")
    val kitPartQuantity: Int? = null
)

