/**
* PartSearch Api
* Search for products and retrieve details and pricing.
*
* The version of the OpenAPI document: v3
* Contact: api.support@digikey.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package net.jastrab.model.partsearch

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Parameters for filtering that are limited to parameters for the products in the response.
 * @param values List of values for the parameter that are contained in the products.
 * @param parameterId The Id of the parameter.
 * @param parameter The name of the parameter.
 */

data class LimitedParameter (
    /* List of values for the parameter that are contained in the products. */
    @JsonProperty("Values")
    val values: List<ValuePair> = ArrayList(),
    /* The Id of the parameter. */
    @JsonProperty("ParameterId")
    val parameterId: Int? = null,
    /* The name of the parameter. */
    @JsonProperty("Parameter")
    val parameter: String? = null
)

