/**
 * PartSearch Api
 * Search for products and retrieve details and pricing.
 *
 * The version of the OpenAPI document: v3
 * Contact: api.support@digikey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package net.jastrab.model.partsearch

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A value belonging to a parameter.
 * @param valueId The Id of the value.
 * @param value The name of the value.
 */

data class ValuePair(
    /* The Id of the value. */
    @JsonProperty("ValueId")
    val valueId: String? = null,
    /* The name of the value. */
    @JsonProperty("Value")
    val value: String? = null
)

